[package]
name = "app"
version = "1.0.0"
authors = ["CESS Labs"]
build = "build.rs"

[lib]
name = "kaleido"
path = "src/main.rs"
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.21.0"

[dependencies]
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_urts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
hex = "0.4"

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_types = { path = "../teaclave-sgx-sdk/sgx_types" }
sgx_urts = { path = "../teaclave-sgx-sdk/sgx_urts" }